"""
Generate the markdown production plan document from solver output.
Includes per-sub-factory machine tables, interface flow tables, raw consumption, totals.
"""

from collections import defaultdict
from typing import Dict, List

from recipes import RECIPES, BUILDINGS, RAW_INPUTS, SUB_FACTORIES, TARGETS, find_subfactory
from solver import solve, compute_machine_details


def compute_interface_flows(production: Dict[str, float]) -> Dict[tuple, Dict[str, float]]:
    """
    For each recipe being run, look at its inputs. For each input that comes from
    a different sub-factory (or is raw), record the flow.

    Returns: {(producer_subfactory, consumer_subfactory): {item: rate_per_min}}
    Special producer label "RAW" for raw inputs.
    """
    flows: Dict[tuple, Dict[str, float]] = defaultdict(lambda: defaultdict(float))

    for item, rate in production.items():
        if item not in RECIPES:
            continue
        recipe = RECIPES[item]
        consumer_sf = find_subfactory(item)
        if consumer_sf is None:
            consumer_sf = "Unknown"

        # How many machine-equivalents are running for this output?
        per_machine = recipe.outputs[item]
        n_fractional = rate / per_machine

        for inp, in_rate_per_machine in recipe.inputs.items():
            consumed = in_rate_per_machine * n_fractional
            if inp in RAW_INPUTS:
                producer_sf = "RAW"
            else:
                producer_sf = find_subfactory(inp) or "Unknown"
            if producer_sf != consumer_sf:
                flows[(producer_sf, consumer_sf)][inp] += consumed

    return flows


def fmt_num(n: float) -> str:
    """Format a number nicely - integer if whole, 2 decimals otherwise."""
    if abs(n - round(n)) < 0.01:
        return f"{round(n):,}"
    return f"{n:,.2f}"


def generate_markdown(targets: Dict[str, float]) -> str:
    result = solve(targets)
    details = compute_machine_details(result["production"])
    flows = compute_interface_flows(result["production"])

    # Aggregate per sub-factory
    by_sf = defaultdict(lambda: {"items": [], "power": 0, "machines": 0,
                                   "fnd_bare": 0, "fnd_clear": 0})
    for d in details:
        sf = d["subfactory"] or "Unknown"
        by_sf[sf]["items"].append(d)
        by_sf[sf]["power"] += d["power_mw"]
        by_sf[sf]["machines"] += d["machines_full"]
        by_sf[sf]["fnd_bare"] += d["foundations_bare"]
        by_sf[sf]["fnd_clear"] += d["foundations_with_clearance"]

    total_power = sum(d["power_mw"] for d in details)
    total_machines = sum(d["machines_full"] for d in details)
    total_fnd_bare = sum(d["foundations_bare"] for d in details)
    total_fnd_clear = sum(d["foundations_with_clearance"] for d in details)

    md = []
    md.append("# Phase 5 Production Plan")
    md.append("")
    targets_desc = ", ".join(
        f"{item} ({fmt_num(rate)}/min)" for item, rate in targets.items()
    )
    md.append(f"Targets: {targets_desc}.")
    md.append("")
    md.append("Generated by `solver.py` from a recipe DB encoded in `recipes.py`. To re-run with different targets or recipes, edit `TARGETS` in `recipes.py` and re-run `python generate_doc.py > plan.md`. Use `--factor` to scale all targets (e.g. `--factor 0.5` for half rate).")
    md.append("")

    # Summary table
    md.append("## Summary")
    md.append("")
    md.append(f"- **Grand total machines:** {total_machines}")
    md.append(f"- **Grand total avg power:** {fmt_num(total_power)} MW (~{total_power/1000:.1f} GW)")
    md.append(f"- **Grand total foundations:** {total_fnd_bare:,} bare / {total_fnd_clear:,} with belt clearance")
    md.append("")

    md.append("### Per sub-factory")
    md.append("")
    md.append("| Sub-factory | Machines | Avg Power (MW) | Foundations (bare / w/clearance) |")
    md.append("|---|---:|---:|---:|")
    for sf_name in sorted(by_sf.keys()):
        sf = by_sf[sf_name]
        md.append(f"| {sf_name} | {sf['machines']} | {fmt_num(sf['power'])} | "
                  f"{sf['fnd_bare']:,} / {sf['fnd_clear']:,} |")
    md.append("")

    # Foundation accounting note
    md.append("> **Foundation note.** *Bare* counts only the building footprint rounded to the 8m foundation grid. "
              "*With clearance* adds a configured buffer on each side for belt routing, power, and walkways "
              "— a planning estimate.")
    md.append("")

    # Raw inputs and surplus
    md.append("## Raw inputs needed")
    md.append("")
    md.append("These flow in from outside the planned sub-factories (smelting hubs, oil/water/nitrogen extraction, concrete factory, fuel siphoned from power plants).")
    md.append("")
    md.append("| Resource | Items/min |")
    md.append("|---|---:|")
    for item, qty in sorted(result["raw"].items()):
        md.append(f"| {item} | {fmt_num(qty)} |")
    md.append("")

    if result["surplus"]:
        md.append("### Surplus (sink for tickets, or use elsewhere)")
        md.append("")
        md.append("| Item | Items/min |")
        md.append("|---|---:|")
        for item, qty in sorted(result["surplus"].items()):
            md.append(f"| {item} | {fmt_num(qty)} |")
        md.append("")

    # Per sub-factory detail
    md.append("## Sub-factory detail")
    md.append("")

    # Order: Final assembly first, then dependencies
    sf_order = ["Assembly", "Quantum", "Nitrogen", "Aluminum", "Oil",
                "Steel", "Electronics", "Basic"]
    for sf_name in sf_order:
        if sf_name not in by_sf:
            continue
        sf = by_sf[sf_name]
        md.append(f"### {sf_name}")
        md.append("")
        md.append(f"**{sf['machines']} machines · {fmt_num(sf['power'])} MW avg · "
                  f"{sf['fnd_bare']:,}/{sf['fnd_clear']:,} foundations (bare/clearance)**")
        md.append("")

        # Production table
        md.append("| Item | Items/min | Building | Count | Clock | Power (MW) | Foundations (bare/clear) | Recipe |")
        md.append("|---|---:|---|---:|---:|---:|---:|---|")
        # Sort items: alphabetical
        for d in sorted(sf["items"], key=lambda x: x["item"]):
            recipe_label = "alt" if d["is_alternate"] else "std"
            md.append(f"| {d['item']} | {fmt_num(d['rate_per_min'])} | {d['building']} | "
                      f"{d['machines_full']} | {d['clock_pct']:.1f}% | {fmt_num(d['power_mw'])} | "
                      f"{d['foundations_bare']}/{d['foundations_with_clearance']} | {recipe_label} |")
        md.append("")

        # Alternate recipes used in this sub-factory
        sf_alts = sorted(
            (d["item"], d["recipe_name"]) for d in sf["items"] if d["is_alternate"]
        )
        if sf_alts:
            md.append("**Alternate recipes used:**")
            md.append("")
            for item, name in sf_alts:
                md.append(f"- {item}: {name}")
            md.append("")

        # Inputs to this sub-factory (from other sub-factories or raw)
        inputs_to_sf = defaultdict(lambda: defaultdict(float))  # producer -> {item: rate}
        for (prod_sf, cons_sf), items in flows.items():
            if cons_sf == sf_name:
                for item, rate in items.items():
                    inputs_to_sf[prod_sf][item] += rate

        if inputs_to_sf:
            md.append(f"**Inputs to {sf_name}:**")
            md.append("")
            md.append("| From | Item | Items/min |")
            md.append("|---|---|---:|")
            for prod_sf in sorted(inputs_to_sf.keys()):
                for item in sorted(inputs_to_sf[prod_sf].keys()):
                    rate = inputs_to_sf[prod_sf][item]
                    md.append(f"| {prod_sf} | {item} | {fmt_num(rate)} |")
            md.append("")

        # Outputs from this sub-factory (to other sub-factories)
        outputs_from_sf = defaultdict(lambda: defaultdict(float))  # consumer -> {item: rate}
        for (prod_sf, cons_sf), items in flows.items():
            if prod_sf == sf_name:
                for item, rate in items.items():
                    outputs_from_sf[cons_sf][item] += rate

        if outputs_from_sf:
            md.append(f"**Outputs from {sf_name}:**")
            md.append("")
            md.append("| To | Item | Items/min |")
            md.append("|---|---|---:|")
            for cons_sf in sorted(outputs_from_sf.keys()):
                for item in sorted(outputs_from_sf[cons_sf].keys()):
                    rate = outputs_from_sf[cons_sf][item]
                    md.append(f"| {cons_sf} | {item} | {fmt_num(rate)} |")
            md.append("")

    # Master interface table
    md.append("## Master interface table")
    md.append("")
    md.append("Every flow between sub-factories or from raw inputs. Use this to size belts and pipes between factories.")
    md.append("")
    md.append("Belt sizing reference (items/min): Mk1 60, Mk2 120, Mk3 270, Mk4 480, Mk5 780, Mk6 1200.")
    md.append("Pipe sizing reference (m³/min): Mk1 300, Mk2 600.")
    md.append("")
    md.append("| Producer | Consumer | Item | Items/min | Belt/pipe needed |")
    md.append("|---|---|---|---:|---|")

    # Belt sizing helper
    def belt_size(rate: float, item: str) -> str:
        # Fluids: rate is m³/min
        fluids = {"Water", "Crude Oil", "Heavy Oil Residue", "Polymer Resin",
                  "Sulfuric Acid", "Nitric Acid", "Alumina Solution",
                  "Nitrogen Gas", "Excited Photonic Matter", "Dark Matter Residue",
                  "Fuel"}
        if item in fluids:
            if rate <= 300:
                return "Mk1 pipe (300)"
            elif rate <= 600:
                return "Mk2 pipe (600)"
            else:
                n = int(rate / 600) + (1 if rate % 600 else 0)
                return f"{n}× Mk2 pipe"
        else:
            tiers = [(60, "Mk1"), (120, "Mk2"), (270, "Mk3"), (480, "Mk4"), (780, "Mk5"), (1200, "Mk6")]
            for cap, name in tiers:
                if rate <= cap:
                    return f"{name} ({cap})"
            n = int(rate / 1200) + (1 if rate % 1200 else 0)
            return f"{n}× Mk6 belts"

    # Sort flows by (producer, consumer, item)
    flow_rows = []
    for (prod_sf, cons_sf), items in flows.items():
        for item, rate in items.items():
            flow_rows.append((prod_sf, cons_sf, item, rate))
    flow_rows.sort(key=lambda r: (r[0] == "RAW", r[0], r[1], r[2]))

    for prod_sf, cons_sf, item, rate in flow_rows:
        md.append(f"| {prod_sf} | {cons_sf} | {item} | {fmt_num(rate)} | {belt_size(rate, item)} |")
    md.append("")

    # Recipe choices section
    md.append("## Recipe choices used")
    md.append("")
    md.append("All alternates are from the Reddit time/effort optimization ranking (S-tier, A-tier, plus selected B-tier). Conflicts resolved in favor of higher-tier picks; see `recipes.py` for the full list and per-recipe rationale.")
    md.append("")
    md.append("| Item | Recipe |")
    md.append("|---|---|")
    alt_recipes = sorted(
        [(item, RECIPES[item].name) for item in result["production"] if item in RECIPES and RECIPES[item].is_alternate],
        key=lambda x: x[0]
    )
    for item, name in alt_recipes:
        md.append(f"| {item} | {name} (alternate) |")
    md.append("")

    # Building footprint appendix
    md.append("## Appendix: building footprints")
    md.append("")
    md.append("Clearance is extra space per side on each axis (W / L). "
              "All grid dimensions on the 8 m foundation grid.")
    md.append("")
    md.append("| Building | Footprint (m) | Clearance per side (W / L m) | Bare W×L fnd | With clearance W×L fnd | Bare total | +Clearance total |")
    md.append("|---|---|---:|---:|---:|---:|---:|")
    for bname, b in sorted(BUILDINGS.items()):
        w_m, l_m = b.footprint_m
        bfw, bfl = b.foundation_dims
        cfw, cfl = b.clearance_dims
        cw, cl = b.clearance_m
        md.append(f"| {bname} | {w_m}×{l_m} m | {cw} / {cl} m"
                  f" | {bfw}×{bfl} | {cfw}×{cfl} | {b.foundations_bare} | {b.foundations_with_clearance} |")
    md.append("")

    return "\n".join(md)


if __name__ == "__main__":
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        description="Generate the markdown production plan from the recipe DB."
    )
    parser.add_argument(
        "--factor",
        type=float,
        default=1.0,
        help="Multiply all recipe targets by this factor "
             "(e.g. 0.5 for half, 0.25 for quarter, 2 for double). Default 1.0.",
    )
    args = parser.parse_args()

    if args.factor <= 0:
        parser.error("--factor must be greater than 0")

    targets = {item: rate * args.factor for item, rate in TARGETS.items()}
    sys.stdout.buffer.write(generate_markdown(targets).encode("utf-8"))
